image: ubuntu:latest

build:
  stage: build
  before_script:
    - apt update 
    - apt install -y sudo
    - useradd -mN runner
    - echo "runner ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/90-runner
    - sudo apt update \
    - apt install -y sudo git cmake libboost-dev g++ build-essential libssl-dev default-jdk python3 python3-pip liblz4-dev rpm
    - pip3 install virtualenv
    - apt install -y dirmngr gnupg apt-transport-https ca-certificates
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
    - echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" > /etc/apt/sources.list.d/mono-official-stable.list
    - apt update
    - apt install -y mono-complete

  script:
    - cmake -E make_directory bld
    - cd bld
    - cmake -D FDB_RELEASE=ON -D GENERATE_DEBUG_PACKAGES=OFF ..
    - make
    - cpack -G RPM

  artifacts:
    paths:
      - "bld/packages/foundationdb-*.rpm*"

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
