name: Build

on:
  push:
    branches: [os-fork-6.2]

env: []
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)

jobs:
  build-linux:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      run: sudo apt update && sudo apt install -y  libboost-dev
      # run: sudo apt update && sudo apt install -y  libfftw3-dev zlib1g-dev libwavpack-dev libwxgtk3.0-gtk3-dev libudev-dev libjack-dev libasound2-dev

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/bld

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/bld
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake -D FDB_RELEASE=ON $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{github.workspace}}/bld
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: make -j2

    - name: Build rpm
      working-directory: ${{github.workspace}}/bld
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cpack -G RPM

    - name: Upload the Result
      uses: actions/upload-artifact@v2
      with:
        path: ${{github.workspace}}/bld/packages/foundationdb-*.rpm*
